project:
  type: website
  output-dir: docs

website:
  title: "Concurso BRDE"
  navbar:
    left:
      - href: index.qmd
      - href: banco_dados.qmd
        text: Banco de Dados
      - href: fundamentos_bd.qmd
        text: Fundamentos de Banco de Dados
      - menu:
          - bd_transacao.qmd
          - integracao_dados.qmd
      - href: analise_dados.qmd
        text: Análise de Dados e Informação
      - menu:
          - dado_info.qmd
          - conceitos_bi.qmd
          - olap.qmd
          - data_warehouse.qmd
      - href: gerenciamento_projetos.qmd
        text: Gerenciamento de Projetos
      - menu:
          - scrum.qmd
      - href: governanca_ti.qmd
        text: Governança de TI


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

