project:
  type: website
  output-dir: docs

website:
  title: "Concurso BRDE"
  navbar:
    left:
      - href: banco_dados.qmd
        text: Banco de Dados
      - menu:
          - normalizacao.qmd
      - href: fundamentos_bd.qmd
        text: Fund. Banco de Dados
      - menu:
          - bd_transacao.qmd
          - integracao_dados.qmd
          - bd_diferenciacao.qmd
      - href: analise_dados.qmd
        text: Análise de Dados
      - menu:
          - dado_info.qmd
          - conceitos_bi.qmd
          - olap.qmd
          - data_warehouse.qmd
      - href: gerenciamento_projetos.qmd
        text: Ger. Projetos
      - menu:
          - scrum.qmd
          - pmbok.qmd
      - href: governanca_ti.qmd
        text: Gov. TI
      - menu:
          - itil.qmd
          - itil_praticas.qmd
      - href: rac_logico.qmd
        text: Rac. Lógico
      - menu:
          -  proposicoes.qmd
          -  tabelas.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

