project:
  type: website
  output-dir: docs

website:
  title: "Concurso BRDE"
  navbar:
    left:
      - href: index.qmd
      - href: banco_dados.qmd
        text: Banco de Dados
      - href: governanca_ti.qmd
        text: Governança de TI


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

