---
title: "Dados Faltantes"
---

## Itens do Edital:

c\) **Análise de dados e informações**: Tratamento de dados faltantes

## [A prevenção e o tratamento dos dados ausentes](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3668100/)

Dados ausentes (ou valores ausentes) são definidos como o valor de dados que não é armazenado para uma variável na observação de interesse.

A falta de dados apresenta vários problemas. Primeiro, a ausência de dados **reduz o poder estatístico**, que se refere à probabilidade de o teste rejeitar a hipótese nula quando ela é falsa. Em segundo lugar, os dados perdidos podem c**ausar viés na estimativa dos parâmetros**. Em terceiro lugar, **pode reduzir a representatividade das amostras**. Em quarto lugar, **pode complicar a análise do estudo**. Cada uma dessas distorções pode **ameaçar a validade dos ensaios e pode levar a conclusões inválidas**.

### Tipos de dados ausentes

#### Faltando completamente ao acaso

Faltando completamente ao acaso (MCAR) é definido como quando a probabilidade de que os dados estejam faltando não está relacionada ao valor específico que se supõe ser obtido ou ao conjunto de respostas observadas. MCAR é uma suposição ideal, mas irracional, para muitos estudos realizados no campo da anestesiologia. No entanto, se os dados estiverem faltando por projeto, devido a uma falha do equipamento ou porque as amostras foram perdidas em trânsito ou tecnicamente insatisfatórias, tais dados são considerados MCAR.

A vantagem estatística dos dados que são MCAR é que a análise permanece imparcial. A energia pode ser perdida no projeto, mas os parâmetros estimados não são influenciados pela ausência dos dados.

#### Faltando ao acaso

Missing at random (MAR) é uma suposição mais realista para os estudos realizados no campo anestésico. Os dados são considerados MAR quando a probabilidade de que as respostas estejam ausentes depende do conjunto de respostas observadas, mas não está relacionada aos valores ausentes específicos que se espera obter.

Como tendemos a considerar a aleatoriedade como não produzindo viés, podemos pensar que o MAR não apresenta um problema. No entanto, MAR não significa que os dados ausentes possam ser ignorados. Se uma variável de abandono for MAR, podemos esperar que a probabilidade de abandono da variável em cada caso seja condicionalmente independente da variável, que é obtida atualmente e que se espera obter no futuro, dado o histórico da variável obtida antes a esse caso.

#### Faltando não ao acaso

Se os caracteres dos dados não atenderem aos de MCAR ou MAR, eles se enquadram na categoria de falta não aleatória (MNAR).

Os casos de dados MNAR são problemáticos. A única maneira de obter uma estimativa imparcial dos parâmetros em tal caso é modelar os dados ausentes. O modelo pode então ser incorporado a um modelo mais complexo para estimar os valores ausentes.

### Técnicas para lidar com os dados ausentes

#### Listwise ou exclusão de caso

De longe, a abordagem mais comum para os dados ausentes é simplesmente omitir os casos com os dados ausentes e analisar os dados restantes. Essa abordagem é conhecida como análise de caso completo (ou caso disponível) ou exclusão de lista.

A exclusão Listwise é o método usado com mais frequência para lidar com dados ausentes e, portanto, tornou-se a opção padrão para análise na maioria dos pacotes de software estatístico. Alguns pesquisadores insistem que isso pode introduzir viés na estimativa dos parâmetros. No entanto, se a suposição de MCAR for satisfeita, sabe-se que uma exclusão de lista produz estimativas imparciais e resultados conservadores. Quando os dados não cumprem a suposição de MCAR, a exclusão listwise pode causar viés nas estimativas dos parâmetros.

Se houver uma amostra grande o suficiente, onde a potência não é um problema e a suposição de MCAR for satisfeita, a exclusão de lista pode ser uma estratégia razoável. No entanto, quando não há uma amostra grande ou a suposição de MCAR não é satisfeita, a exclusão de lista não é a estratégia ideal.

#### Exclusão de pares

A exclusão de pares elimina informações apenas quando o ponto de dados específico necessário para testar uma suposição específica está ausente. Se houver dados ausentes em outro lugar no conjunto de dados, os valores existentes serão usados no teste estatístico. Como uma exclusão pairwise usa todas as informações observadas, ela preserva mais informações do que a exclusão listwise, que pode excluir o caso com quaisquer dados ausentes. Esta abordagem apresenta os seguintes problemas: 1) os parâmetros do modelo estarão em diferentes conjuntos de dados com diferentes estatísticas, como tamanho da amostra e erros padrão; e 2) pode produzir uma matriz de intercorrelação que não é positiva definida, o que provavelmente impedirá uma análise mais aprofundada.

A exclusão de pares é conhecida por ser menos tendenciosa para os dados MCAR ou MAR, e os mecanismos apropriados são incluídos como covariáveis. No entanto, se houver muitas observações ausentes, a análise será deficiente.

#### Substituição média

Em uma substituição média, o valor médio de uma variável é usado no lugar do valor de dados ausentes para essa mesma variável. Isso permite que os pesquisadores utilizem os dados coletados em um conjunto de dados incompleto. O fundamento teórico da substituição da média é que a média é uma estimativa razoável para uma observação selecionada aleatoriamente de uma distribuição normal. No entanto, com valores ausentes que não são estritamente aleatórios, especialmente na presença de uma grande desigualdade no número de valores ausentes para as diferentes variáveis, o método de substituição de média pode levar a um viés inconsistente. Além disso, esta abordagem não adiciona novas informações, mas apenas aumenta o tamanho da amostra e leva a uma subestimação dos erros. Assim, a substituição média não é geralmente aceita.

#### Imputação de regressão

A imputação é o processo de substituir os dados perdidos por valores estimados. Em vez de excluir qualquer caso que tenha algum valor ausente, essa abordagem preserva todos os casos substituindo os dados ausentes por um valor provável estimado por outras informações disponíveis. Após todos os valores ausentes terem sido substituídos por esta abordagem, o conjunto de dados é analisado usando as técnicas padrão para dados completos.

Na imputação de regressão, as variáveis existentes são usadas para fazer uma previsão e, em seguida, o valor previsto é substituído como se fosse um valor real obtido. Essa abordagem tem várias vantagens, porque a imputação retém uma grande quantidade de dados sobre a exclusão de lista ou de pares e evita alterar significativamente o desvio padrão ou a forma da distribuição. No entanto, como em uma substituição de média, enquanto uma imputação de regressão substitui um valor que é previsto de outras variáveis, nenhuma informação nova é adicionada, enquanto o tamanho da amostra foi aumentado e o erro padrão foi reduzido.

### Última observação realizada

No campo da pesquisa em anestesiologia, muitos estudos são realizados com a abordagem longitudinal ou de séries temporais, nas quais os sujeitos são medidos repetidamente em uma série de pontos no tempo. Um dos métodos de imputação mais amplamente utilizados nesse caso é a última observação realizada (LOCF). Este método substitui cada valor ausente pelo último valor observado do mesmo assunto. Sempre que faltar um valor, este é substituído pelo último valor observado.

Este método é vantajoso, pois é fácil de entender e comunicar entre os estatísticos e os clínicos ou entre um patrocinador e o pesquisador.

Embora simples, esse método assume fortemente que o valor do resultado permanece inalterado pelos dados ausentes, o que parece improvável em muitos cenários (especialmente nas tentativas anestésicas). Produz uma estimativa enviesada do efeito do tratamento e subestima a variabilidade do resultado estimado. Consequentemente, a Academia Nacional de Ciências recomendou contra o uso acrítico da imputação simples, incluindo LOCF e a observação de linha de base realizada, afirmando que:

Métodos de imputação única, como a última observação realizada e a observação da linha de base, não devem ser usados como a abordagem principal para o tratamento de dados ausentes, a menos que as suposições subjacentes sejam cientificamente justificadas.

#### Probabilidade máxima

Existem várias estratégias que usam o método de máxima verossimilhança para lidar com os dados ausentes. Neles, a suposição de que os dados observados são uma amostra extraída de uma distribuição normal multivariada é relativamente fácil de entender. Depois que os parâmetros são estimados usando os dados disponíveis, os dados ausentes são estimados com base nos parâmetros que acabaram de ser estimados.

Quando há dados ausentes, mas relativamente completos, as estatísticas que explicam as relações entre as variáveis podem ser calculadas usando o método de máxima verossimilhança. Ou seja, os dados perdidos podem ser estimados usando a distribuição condicional das outras variáveis.

#### Expectativa-Maximização

Expectation-Maximization (EM) é um tipo de método de máxima verossimilhança que pode ser usado para criar um novo conjunto de dados, no qual todos os valores ausentes são imputados com valores estimados pelos métodos de máxima verossimilhança. Essa abordagem começa com a etapa de expectativa, durante a qual os parâmetros (por exemplo, variâncias, covariâncias e médias) são estimados, talvez usando a exclusão listwise. Essas estimativas são usadas para criar uma equação de regressão para prever os dados ausentes. A etapa de maximização usa essas equações para preencher os dados ausentes. A etapa de expectativa é então repetida com os novos parâmetros, onde as novas equações de regressão são determinadas para "preencher" os dados ausentes. As etapas de expectativa e maximização são repetidas até que o sistema se estabilize, quando a matriz de covariância para a iteração subsequente é virtualmente a mesma da iteração anterior.

Uma característica importante da imputação de maximização de expectativa é que, quando o novo conjunto de dados sem valores ausentes é gerado, um termo de perturbação aleatório para cada valor imputado é incorporado para refletir a incerteza associada à imputação. No entanto, a imputação de maximização de expectativa tem algumas desvantagens. Essa abordagem pode levar muito tempo para convergir, especialmente quando há uma grande fração de dados ausentes, e é muito complexa para ser aceita por alguns estatísticos excepcionais. Essa abordagem pode levar a estimativas de parâmetros enviesadas e subestimar o erro padrão.

Para o método de imputação de maximização de expectativa, um valor predito com base nas variáveis disponíveis para cada caso é substituído pelos dados ausentes. Como uma única imputação omite as possíveis diferenças entre as múltiplas imputações, uma única imputação tenderá a subestimar os erros padrão e, assim, superestimar o nível de precisão. Assim, uma única imputação dá ao pesquisador mais poder aparente do que os dados na realidade.

#### Imputação múltipla

A imputação múltipla é outra estratégia útil para lidar com os dados ausentes. Em uma imputação múltipla, em vez de substituir um único valor para cada dado ausente, os valores ausentes são substituídos por um conjunto de valores plausíveis que contêm a variabilidade natural e a incerteza dos valores corretos.

Esta abordagem começa com uma previsão dos dados perdidos usando os dados existentes de outras variáveis . Os valores ausentes são substituídos pelos valores previstos e um conjunto de dados completo chamado conjunto de dados imputados é criado. Este processo itera a repetibilidade e cria vários conjuntos de dados imputados (daí o termo "imputação múltipla"). Cada conjunto de dados imputados múltiplos produzido é então analisado usando os procedimentos de análise estatística padrão para dados completos e fornece resultados de análises múltiplas. Posteriormente, combinando esses resultados de análise, um único resultado de análise geral é produzido.

O benefício da imputação múltipla é que, além de restaurar a variabilidade natural dos valores ausentes, ela incorpora a incerteza devido aos dados ausentes, o que resulta em uma inferência estatística válida. Restaurar a variabilidade natural dos dados ausentes pode ser obtido substituindo os dados ausentes pelos valores imputados que são previstos usando as variáveis correlacionadas com os dados ausentes. A incorporação da incerteza é feita produzindo diferentes versões dos dados ausentes e observando a variabilidade entre os conjuntos de dados imputados.

Foi demonstrado que a imputação múltipla produz inferência estatística válida que reflete a incerteza associada à estimativa dos dados ausentes. Além disso, a imputação múltipla revela-se robusta à violação dos pressupostos de normalidade e produz resultados adequados mesmo na presença de um pequeno tamanho amostral ou de um elevado número de dados perdidos.

Com o desenvolvimento de novos softwares estatísticos, embora os princípios estatísticos da imputação múltipla possam ser difíceis de entender, a abordagem pode ser utilizada facilmente.

#### Análise sensitiva

A análise de sensibilidade é definida como o estudo que define como a incerteza na saída de um modelo pode ser alocada para as diferentes fontes de incerteza em suas entradas.

Ao analisar os dados ausentes, suposições adicionais sobre os motivos dos dados ausentes são feitas e essas suposições geralmente são aplicáveis à análise primária. No entanto, as suposições não podem ser definitivamente validadas quanto à correção. Portanto, o National Research Council propôs que a análise de sensibilidade fosse realizada para avaliar a robustez dos resultados aos desvios da suposição MAR.

--------------------------------

Fontes: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3668100/
