---
title: "Práticas ITIL"
---

## Itens do Edital:

g\) **Governança de TI**: ITIL versão 4 (ITIL 4): Operação de Serviços (Gerenciamento de Eventos, Gerenciamento de Incidentes, Gerenciamento de Problemas, Cumprimento de Requisições, Gerenciamento de Acessos), Desenho de Serviços (Gerenciamento de Níveis de Serviço, Gerenciamento de Capacidade, Gerenciamento de Disponibilidade, Gerenciamento de Continuidade de Serviços de TI, Gerenciamento de Continuidade de Negócio), Transição de Serviços (Gerenciamento de Configuração e Ativos de Serviços de TI, Gerenciamento de Liberação e Implantação, Gerenciamento de Mudanças), Melhoria Contínua de Serviços, Métricas (Fatores Críticos de Sucesso - CSFs, Índices Chave de Performance - KPIs).

## 

**Introdução as práticas da ITIL4**

{{< video https://youtu.be/-C7xVVFTIhk >}}

## [Quais são as práticas de gerenciamento do ITIL 4?](https://www.itgovernance.co.uk/blog/what-are-the-itil-4-management-practices)

O ITIL 4 contém 34 práticas de gerenciamento para ajudar as organizações a fornecer uma entrega de serviço eficaz em toda a cadeia de valor.

Enquanto as versões anteriores do ITIL focavam em serviços de TI, o ITIL 4 expande suas práticas de gerenciamento para incluir também cultura, tecnologia e gerenciamento de dados. Isso reflete uma mudança geral no ITIL 4, afastando-se do pensamento dominante do processo e em direção a uma forma diversa e dinâmica de operação.

Existem três categorias de práticas de gerenciamento ITIL 4, que veremos em profundidade neste blog:

-   **Práticas gerais de gestão** , que se aplicam a toda a organização para o sucesso do negócio e dos serviços que presta.

-   **Práticas de gerenciamento de serviços** , que se aplicam a serviços específicos que estão sendo desenvolvidos, implantados, entregues e suportados.

-   **Práticas de gerenciamento técnico** , que são adaptadas de domínios de gerenciamento de tecnologia para fins de gerenciamento de serviços.

### **Práticas gerais de gerenciamento**

Esta seção contém 14 práticas de gerenciamento:

#### **1. Gerenciamento de arquitetura**

Essa prática ajuda as organizações a gerenciar a maneira muitas vezes complexa em que sua arquitetura organizacional se relaciona com várias partes do negócio.

Ele fornece os princípios, padrões e ferramentas para ajudar a gerenciar mudanças de forma estruturada e ágil.

#### **2. Melhoria contínua**

As organizações devem ser capazes de alinhar seus processos e serviços com as necessidades de negócios em constante mudança.

A prática de melhoria contínua os ajuda a conseguir isso. Ele garante que as organizações identifiquem oportunidades de melhoria nos serviços, componentes de serviço, práticas ou outras partes do gerenciamento de serviço.

#### **3. Gestão da segurança da informação**

Essa prática está relacionada à maneira como uma organização protege suas informações confidenciais contra uso indevido. Especificamente, o gerenciamento de segurança da informação procura maneiras de evitar violações da confidencialidade, integridade e disponibilidade dos dados.

Nesse contexto, a confidencialidade refere-se à informação sendo visualizada apenas por pessoas autorizadas, a integridade da informação sendo precisa e a disponibilidade da informação sendo acessível quando necessário.

#### **4. Gestão do conhecimento**

Essa prática ajuda as organizações a melhorar a maneira como usam os dados. Centra-se na conveniência, eficácia e eficiência do conhecimento e uso de dados.

#### **5. Medição e relatórios**

Para tomar boas decisões e melhorar continuamente os sistemas, as organizações devem realizar pesquisas baseadas em evidências.

Esta prática fornece uma estrutura para fazer isso, recomendando avaliações de risco e coleta de dados relevantes.

#### **6. Gestão de mudanças organizacionais**

Essa prática ajuda as organizações a implementar as mudanças recomendadas durante o processo de melhoria contínua.

Ele enfatiza o aspecto humano da gestão de mudanças e os benefícios duradouros que podem ser obtidos se os desafios e as oportunidades dos indivíduos forem levados em consideração.

#### **7. Gerenciamento de portfólio**

Essa prática garante que a organização tenha a combinação certa de programas, produtos e serviços para atingir seus objetivos.

Ele também considera o financiamento da organização e as restrições de recursos.

#### **8. Gerenciamento de projetos**

Essa prática ajuda as organizações a supervisionar seus projetos em andamento e garantir que sejam entregues com sucesso.

Aborda a forma como os projetos são planejados, delegados, monitorados e mantidos. Aborda também as relações entre as partes interessadas e visa manter os envolvidos no projeto motivados.

#### **9. Gestão de relacionamento**

Para que os projetos sejam bem-sucedidos, as organizações devem estabelecer e nutrir os relacionamentos entre as partes interessadas. Essa prática ajuda as organizações a identificar, analisar, monitorar e melhorar continuamente os relacionamentos.

#### **10. Gestão de riscos**

Essa prática ajuda as organizações a entender e lidar com os riscos. Existem inúmeras maneiras pelas quais os problemas podem se materializar e é essencial que sejam identificados o mais rápido possível para evitar interrupções, consequências financeiras e problemas de sustentabilidade.

#### **11. Gestão financeira do serviço**

Essa prática apóia as estratégias e os planos da organização, garantindo que os recursos financeiros e os investimentos sejam usados ​​de forma eficiente.

#### **12. Gestão da estratégia**

Essa prática ajuda as organizações a definir objetivos específicos e formas de alcançá-los. Também garante que os recursos necessários sejam alocados para atingir essas metas e esclarece as prioridades da organização.

#### **13. Gestão de fornecedores**

As organizações devem gerenciar seus fornecedores de forma eficaz se quiserem garantir a produção e a entrega tranquilas de produtos e serviços.

Essa prática ajuda a fomentar esses relacionamentos, focando na criação de oportunidades de colaboração e na identificação de formas de fazer melhorias.

#### **14. Gestão de talentos da força de trabalho**

Essa prática ajuda as organizações a colocar pessoas talentosas e qualificadas nas funções certas. Ele se concentra no planejamento, recrutamento, integração e treinamento de funcionários.

Também analisa a forma como as organizações avaliam o desempenho dos funcionários e como desenvolver o planejamento de sucessão.

### **Práticas de gerenciamento de serviços**

Esta seção contém mais 17 práticas de gerenciamento:

#### **15. Gerenciamento de disponibilidade**

Com essa prática, as organizações podem garantir que a disponibilidade de produtos e serviços atenda às necessidades do cliente. Essas necessidades devem ter sido acordadas no início do projeto.

#### **16. Análise de negócios**

Essa prática ajuda as organizações a analisar seus processos de negócios ou elementos dentro deles. Destina-se a ajudar a resolver problemas específicos e melhorar a criação de valor para as partes interessadas.

#### **17. Gestão de capacidade e desempenho**

Essa prática ajuda as organizações a garantir que seus produtos e serviços atendam aos níveis de desempenho esperados. Ele também atende às demandas atuais e futuras, ajudando as organizações a identificar quaisquer mudanças que possam afetar sua capacidade.

#### **18. Habilitação de mudança**

Essa prática garante que as organizações maximizem as mudanças de TI bem-sucedidas. Ele faz isso garantindo que as avaliações de risco sejam realizadas, que as autorizações apropriadas estejam em vigor para implementar mudanças e que as mudanças sejam gerenciadas com eficiência.

#### **19. Gestão de incidentes**

O objetivo desta prática é mitigar o impacto negativo de incidentes disruptivos. Ele ajuda as organizações a identificar maneiras de restaurar a operação normal do serviço o mais rápido possível.

#### **20. Gerenciamento de ativos de TI**

Essa prática ajuda as organizações a gerenciar o ciclo de vida completo de seus ativos de TI. Baseia-se na maximização de valor, controle de custos, gestão de riscos, tomada de decisão, gestão de reutilização de ativos e aposentadoria.

Também aborda os requisitos regulatórios e contratuais relacionados aos ativos de TI.

#### **21. Monitoramento e gerenciamento de eventos**

Com essa prática, as organizações podem observar sistematicamente serviços e componentes de serviço, além de registrar e relatar alterações selecionadas.

Eles podem fazer isso identificando e priorizando infraestrutura, serviços, processos de negócios e eventos de segurança da informação. A prática também estabelece as respostas a esses eventos.

#### **22. Gerenciamento de problemas**

Essa prática ajuda as organizações a mitigar o impacto e a probabilidade de eventos disruptivos. Ele faz isso concentrando-se na identificação de possíveis causas de incidentes e nas formas de navegar por eles.

#### **23. Gerenciamento de liberação**

Essa prática se concentra na maneira como os serviços são implantados. Ele aborda serviços e recursos novos e alterados.

#### **24. Gerenciamento do catálogo de serviços**

Essa prática garante que as organizações tenham uma única fonte de informações consistentes para todos os seus serviços. Garante que a informação esteja disponível para públicos relevantes sempre que necessário.

#### **25. Gerenciamento de configuração de serviço**

Essa prática garante que as informações sobre a configuração dos serviços de uma organização permaneçam disponíveis e precisas. Ele também aborda os itens de configuração que suportam esses serviços.

#### **26. Gestão da continuidade do serviço**

Esta prática fornece uma estrutura para a construção de resiliência organizacional. Ele ajuda as organizações a proteger os serviços no caso de um incidente perturbador e garantir que sua disponibilidade e desempenho permaneçam em um nível suficiente.

#### **27. Projeto de serviço**

Essa prática ajuda as organizações a projetar produtos e serviços adequados ao uso e alinhados com o propósito definido. Também garante que os serviços possam ser entregues com sucesso pela organização em seu ecossistema atual.

A prática tem como foco o planejamento de produtos e serviços, bem como a gestão de pessoas, parceiros, fornecedores, informação, redes de comunicação e tecnologia.

#### **28. Balcão de atendimento**

Essa prática ajuda as organizações a capturar a demanda por resolução de incidentes e solicitações de serviço. Deve também ser o ponto de contacto do prestador de serviços e dos seus utilizadores.

#### **29. Gerenciamento do nível de serviço**

Essa prática define metas de negócios para a execução dos serviços. Ele garante que a prestação de serviços possa ser avaliada adequadamente, permitindo que a organização identifique problemas e melhore suas práticas.

#### **30. Gerenciamento de solicitação de serviço**

Com essa prática, as organizações podem oferecer suporte à qualidade de serviço acordada ao lidar com todas as solicitações de serviço predefinidas e iniciadas pelo usuário de maneira eficaz e amigável.

#### **31. Validação e teste do serviço**

Essa prática garante que produtos e serviços novos ou alterados atendam aos requisitos definidos.

As organizações devem fazer isso medindo o valor do serviço com base nas informações dos clientes, objetivos de negócios e requisitos regulamentares.

### **Práticas de gestão técnica**

Esta seção contém as três práticas de gerenciamento finais:

#### **32. Gerenciamento de implantação**

As práticas de gerenciamento de implantação ajudam as organizações a mover hardware, software, documentação e processos novos ou alterados de um ambiente de produção para um ambiente ativo.

Também os ajuda a mover esses componentes para outros ambientes para teste ou preparação.

#### **33. Gerenciamento de infraestrutura e plataforma**

Essa prática ajuda as organizações a supervisionar sua infraestrutura e plataformas, permitindo que monitorem tecnologias implantadas internamente e por provedores de serviços.

#### **34. Desenvolvimento e gerenciamento de software**

Essa prática garante que os aplicativos atendam às necessidades das partes interessadas. Ele aborda a funcionalidade do software, confiabilidade, manutenção, conformidade e sua capacidade de ser auditado.

------------------------------------------------------------------------

Fontes: https://www.itgovernance.co.uk/blog/what-are-the-itil-4-management-practices
