---
title: "Procedimentos, Funções, Visões e gatilhos"
---

## Itens do Edital:

b\) **Fundamentos de Banco de Dados**: Conceitos: Sistemas de gerência de banco de dados (SGBD), Arquitetura, modelos lógicos e representação física; Organização física e métodos de acesso; Conceito de transação, concorrência, recuperação, integridade; Linguagens de definição (DDL) e manipulação de dados (DML) em SGBDs relacionais; Procedimentos (stored procedures), funções (functions), visões (views), visões materializadas (materialized views) e gatilhos (triggers), Linguagem de consulta estruturada (SQL, Avaliação de modelos de dados, Técnicas de engenharia reversa para criação e atualização de modelos de dados, Integração dos dados (ETL, Transferência de Arquivos e Integração via Base de Dados, Data Lakes e Soluções para Big Data, Diferenciação entre bancos relacionais, multidimensionais, documentos e grafos.

## Stored Procedures

{{< video https://youtu.be/MjE3kv9vGIg >}}

## Views

{{< video https://youtu.be/CYp8_VpTbMw >}}

## Funções

## 

Triggers

{{< video https://youtu.be/U5hmVEnx_7M >}}

{{< video https://youtu.be/EkSTkplF9A0 >}}
